spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  config:
    import: "classpath:openai-config.yaml"
  ai:
    openai:
      base-url: https://api.openai.com/
      api-key: sk-xxx
      chat:
        options:
          model: gpt-3.5-turbo # 模型默认配置
  application:
    name: miaogu_aichat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ry-vue?severTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
  graphql:
    cors:
      allowed-origins: http://localhost:5173

logging:
  level:
    root: info

server:
  port: 8088
  address: 0.0.0.0

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true
jwt:
  fixed-rate: 8
  refresh-expire: 86400000
  expire: 3600000
#打印sql语句到控台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    type-aliases-package: com.miaogu.entity
debug: true
